"""nullable setup

Revision ID: 07577d076471
Revises: 3a325121ca6e
Create Date: 2023-12-23 18:45:57.537340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07577d076471'
down_revision: Union[str, None] = '3a325121ca6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banned_users', 'tg_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('roles', 'role_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('student_additional_info', 'room_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('student_additional_info', 'is_male',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('users', 'surname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('users', 'tg_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'score',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'score',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'tg_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('users', 'surname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('student_additional_info', 'is_male',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('student_additional_info', 'room_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('roles', 'role_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('banned_users', 'tg_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
