"""group number

Revision ID: 4ba5bc2ef03b
Revises: 07577d076471
Create Date: 2023-12-23 18:47:13.335284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ba5bc2ef03b'
down_revision: Union[str, None] = '07577d076471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_additional_info', sa.Column('group_number', sa.String(length=32), nullable=True))
    op.alter_column('student_additional_info', 'room_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('student_additional_info', 'is_male',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_additional_info', 'is_male',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('student_additional_info', 'room_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('student_additional_info', 'group_number')
    # ### end Alembic commands ###
