name: "Telegram Notifier Service Build"
on: push
jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.PAT }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./TelegramNotifierService/TelegramNotifierService/
          file: ./TelegramNotifierService/TelegramNotifierService/Dockerfile
          push: true
          tags: hsse-bot/telegram-notifier-service:latest
          
