
name: "Users Managing Service Build"
on: 
  push:
    branches: master
jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.PAT }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./users_managing_service
          file: ./users_managing_service/Dockerfile
          push: true
          tags: ghcr.io/hsse-bot/users-managing-service:latest
          
